[project]
name = "acp.nvim"
version = "0.1.0"
description = "Test suite for unnest.nvim"
requires-python = ">=3.12"
dependencies = [
    "pynvim",
    "pytest",
    "pytest-rerunfailures",
    "agent-client-protocol",
    "requests",
    "pillow>=12.1.1",
    "pyqt6>=6.10.2",
    "pyobjc-framework-Cocoa>=11.1; sys_platform == 'darwin'",
]

# [tool.uv]
# required-environments = [
#   "sys_platform == 'linux'",
#   "sys_platform == 'darwin'",
#   "sys_platform == 'win32'"
# ]
