--- This file was generated by ./scripts/convert_schema.lua. Do not edit it manually

---Capabilities supported by the agent.
---
---Advertised during initialization to inform the client about
---available features and content types.
---
---See protocol docs: [Agent Capabilities](https://agentclientprotocol.com/protocol/initialization#agent-capabilities)
---@class acp.AgentCapabilities
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field loadSession boolean? Whether the agent supports `session/load`.
---@field mcpCapabilities acp.McpCapabilities? MCP capabilities supported by the agent.
---@field promptCapabilities acp.PromptCapabilities? Prompt capabilities supported by the agent.
---@field sessionCapabilities acp.SessionCapabilities?

---Optional annotations for the client. The client can use annotations to inform how objects are used or displayed
---@class acp.Annotations
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field audience acp.Role[]|nil?
---@field lastModified string|nil?
---@field priority number|nil?

---Audio provided to or from an LLM.
---@class acp.AudioContent
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field annotations acp.Annotations|nil?
---@field data string
---@field mimeType string

---Describes an available authentication method.
---@class acp.AuthMethod
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field description string|nil? Optional description providing more details about this authentication method.
---@field id string Unique identifier for this authentication method.
---@field name string Human-readable name of the authentication method.

---Request parameters for the authenticate method.
---
---Specifies which authentication method to use.
---@class acp.AuthenticateRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field methodId string The ID of the authentication method to use. Must be one of the methods advertised in the initialize response.

---Response to the `authenticate` method.
---@class acp.AuthenticateResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)

---Information about a command.
---@class acp.AvailableCommand
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field description string Human-readable description of what the command does.
---@field input acp.AvailableCommandInput|nil? Input for the command if required
---@field name string Command name (e.g., `create_plan`, `research_codebase`).

---The input specification for a command.

---All text that was typed after the command name is provided as input.
---@class acp.AvailableCommandInput_unstructured : acp.UnstructuredCommandInput
---@alias acp.AvailableCommandInput acp.AvailableCommandInput_unstructured

---Available commands are ready or have changed
---@class acp.AvailableCommandsUpdate
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field availableCommands acp.AvailableCommand[] Commands the agent can execute

---Binary resource contents.
---@class acp.BlobResourceContents
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field blob string
---@field mimeType string|nil?
---@field uri string

---Notification to cancel ongoing operations for a session.
---
---See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
---@class acp.CancelNotification
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The ID of the session to cancel operations for.

---Capabilities supported by the client.
---
---Advertised during initialization to inform the agent about
---available features and methods.
---
---See protocol docs: [Client Capabilities](https://agentclientprotocol.com/protocol/initialization#client-capabilities)
---@class acp.ClientCapabilities
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field fs acp.FileSystemCapability? File system capabilities supported by the client. Determines which file operations the agent can request.
---@field terminal boolean? Whether the Client support all `terminal/*` methods.

---Session configuration options have been updated.
---@class acp.ConfigOptionUpdate
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field configOptions acp.SessionConfigOption[] The full set of configuration options and their current values.

---Standard content block (text, images, resources).
---@class acp.Content
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content acp.ContentBlock The actual content block.

---Content blocks represent displayable information in the Agent Client Protocol.
---
---They provide a structured way to handle various types of user-facing content—whether
---it's text from language models, images for analysis, or embedded resources for context.
---
---Content blocks appear in:
---- User prompts sent via `session/prompt`
---- Language model output streamed through `session/update` notifications
---- Progress updates and results from tool calls
---
---This structure is compatible with the Model Context Protocol (MCP), enabling
---agents to seamlessly forward content from MCP tool outputs without transformation.
---
---See protocol docs: [Content](https://agentclientprotocol.com/protocol/content)

---Text content. May be plain text or formatted with Markdown.  All agents MUST support text content blocks in prompts. Clients SHOULD render this text as Markdown.
---@class acp.ContentBlock_1 : acp.TextContent
---@field type "text"

---Images for visual context or analysis.  Requires the `image` prompt capability when included in prompts.
---@class acp.ContentBlock_2 : acp.ImageContent
---@field type "image"

---Audio data for transcription or analysis.  Requires the `audio` prompt capability when included in prompts.
---@class acp.ContentBlock_3 : acp.AudioContent
---@field type "audio"

---References to resources that the agent can access.  All agents MUST support resource links in prompts.
---@class acp.ContentBlock_4 : acp.ResourceLink
---@field type "resource_link"

---Complete resource contents embedded directly in the message.  Preferred for including context as it avoids extra round-trips.  Requires the `embeddedContext` prompt capability when included in prompts.
---@class acp.ContentBlock_5 : acp.EmbeddedResource
---@field type "resource"
---@alias acp.ContentBlock acp.ContentBlock_1|acp.ContentBlock_2|acp.ContentBlock_3|acp.ContentBlock_4|acp.ContentBlock_5

---A streamed item of content
---@class acp.ContentChunk
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content acp.ContentBlock A single item of content

---Request to create a new terminal and execute a command.
---@class acp.CreateTerminalRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field args string[]? Array of command arguments.
---@field command string The command to execute.
---@field cwd string|nil? Working directory for the command (absolute path).
---@field env acp.EnvVariable[]? Environment variables for the command.
---@field outputByteLimit number|nil? Maximum number of output bytes to retain.  When the limit is exceeded, the Client truncates from the beginning of the output to stay within the limit.  The Client MUST ensure truncation happens at a character boundary to maintain valid string output, even if this means the retained output is slightly less than the specified limit.
---@field sessionId acp.SessionId The session ID for this request.

---Response containing the ID of the created terminal.
---@class acp.CreateTerminalResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field terminalId string The unique identifier for the created terminal.

---The current mode of the session has changed
---
---See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
---@class acp.CurrentModeUpdate
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field currentModeId acp.SessionModeId The ID of the current mode

---A diff representing file modifications.
---
---Shows changes to files in a format suitable for display in the client UI.
---
---See protocol docs: [Content](https://agentclientprotocol.com/protocol/tool-calls#content)
---@class acp.Diff
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field newText string The new content after modification.
---@field oldText string|nil? The original content (None for new files).
---@field path string The file path being modified.

---The contents of a resource, embedded into a prompt or tool call result.
---@class acp.EmbeddedResource
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field annotations acp.Annotations|nil?
---@field resource acp.EmbeddedResourceResource

---Resource content that can be embedded in a message.

---@class acp.EmbeddedResourceResource_TextResourceContents : acp.TextResourceContents

---@class acp.EmbeddedResourceResource_BlobResourceContents : acp.BlobResourceContents
---@alias acp.EmbeddedResourceResource acp.EmbeddedResourceResource_TextResourceContents|acp.EmbeddedResourceResource_BlobResourceContents

---An environment variable to set when launching an MCP server.
---@class acp.EnvVariable
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field name string The name of the environment variable.
---@field value string The value to set for the environment variable.

---JSON-RPC error object.
---
---Represents an error that occurred during method execution, following the
---JSON-RPC 2.0 error object specification with optional additional data.
---
---See protocol docs: [JSON-RPC Error Object](https://www.jsonrpc.org/specification#error_object)
---@class acp.Error
---@field code acp.ErrorCode A number indicating the error type that occurred. This must be an integer as defined in the JSON-RPC specification.
---@field data any? Optional primitive or structured value that contains additional information about the error. This may include debugging information or context-specific details.
---@field message string A string providing a short description of the error. The message should be limited to a concise single sentence.

---Predefined error codes for common JSON-RPC and ACP-specific errors.
---
---These codes follow the JSON-RPC 2.0 specification for standard errors
---and use the reserved range (-32000 to -32099) for protocol-specific errors.

---**Parse error**: Invalid JSON was received by the server. An error occurred on the server while parsing the JSON text.
---@class acp.ErrorCode_Parse error

---**Invalid request**: The JSON sent is not a valid Request object.
---@class acp.ErrorCode_Invalid request

---**Method not found**: The method does not exist or is not available.
---@class acp.ErrorCode_Method not found

---**Invalid params**: Invalid method parameter(s).
---@class acp.ErrorCode_Invalid params

---**Internal error**: Internal JSON-RPC error. Reserved for implementation-defined server errors.
---@class acp.ErrorCode_Internal error

---**Authentication required**: Authentication is required before this operation can be performed.
---@class acp.ErrorCode_Authentication required

---**Resource not found**: A given resource, such as a file, was not found.
---@class acp.ErrorCode_Resource not found

---Other undefined error code.
---@class acp.ErrorCode_Other
---@alias acp.ErrorCode acp.ErrorCode_Parse error|acp.ErrorCode_Invalid request|acp.ErrorCode_Method not found|acp.ErrorCode_Invalid params|acp.ErrorCode_Internal error|acp.ErrorCode_Authentication required|acp.ErrorCode_Resource not found|acp.ErrorCode_Other

---Allows the Agent to send an arbitrary notification that is not part of the ACP spec.
---Extension notifications provide a way to send one-way messages for custom functionality
---while maintaining protocol compatibility.
---
---See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@class acp.ExtNotification

---Allows for sending an arbitrary request that is not part of the ACP spec.
---Extension methods provide a way to add custom functionality while maintaining
---protocol compatibility.
---
---See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@class acp.ExtRequest

---Allows for sending an arbitrary response to an [`ExtRequest`] that is not part of the ACP spec.
---Extension methods provide a way to add custom functionality while maintaining
---protocol compatibility.
---
---See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@class acp.ExtResponse

---Filesystem capabilities supported by the client.
---File system capabilities that a client may support.
---
---See protocol docs: [FileSystem](https://agentclientprotocol.com/protocol/initialization#filesystem)
---@class acp.FileSystemCapability
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field readTextFile boolean? Whether the Client supports `fs/read_text_file` requests.
---@field writeTextFile boolean? Whether the Client supports `fs/write_text_file` requests.

---An HTTP header to set when making requests to the MCP server.
---@class acp.HttpHeader
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field name string The name of the HTTP header.
---@field value string The value to set for the HTTP header.

---An image provided to or from an LLM.
---@class acp.ImageContent
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field annotations acp.Annotations|nil?
---@field data string
---@field mimeType string
---@field uri string|nil?

---Metadata about the implementation of the client or agent.
---Describes the name and version of an MCP implementation, with an optional
---title for UI representation.
---@class acp.Implementation
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field name string Intended for programmatic or logical use, but can be used as a display name fallback if title isn’t present.
---@field title string|nil? Intended for UI and end-user contexts — optimized to be human-readable and easily understood.  If not provided, the name should be used for display.
---@field version string Version of the implementation. Can be displayed to the user or used for debugging or metrics purposes. (e.g. "1.0.0").

---Request parameters for the initialize method.
---
---Sent by the client to establish connection and negotiate capabilities.
---
---See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
---@class acp.InitializeRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field clientCapabilities acp.ClientCapabilities? Capabilities supported by the client.
---@field clientInfo acp.Implementation|nil? Information about the Client name and version sent to the Agent.  Note: in future versions of the protocol, this will be required.
---@field protocolVersion acp.ProtocolVersion The latest protocol version supported by the client.

---Response to the `initialize` method.
---
---Contains the negotiated protocol version and agent capabilities.
---
---See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
---@class acp.InitializeResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field agentCapabilities acp.AgentCapabilities? Capabilities supported by the agent.
---@field agentInfo acp.Implementation|nil? Information about the Agent name and version sent to the Client.  Note: in future versions of the protocol, this will be required.
---@field authMethods acp.AuthMethod[]? Authentication methods supported by the agent.
---@field protocolVersion acp.ProtocolVersion The protocol version the client specified if supported by the agent, or the latest protocol version supported by the agent.  The client should disconnect, if it doesn't support this version.

---Request to kill a terminal command without releasing the terminal.
---@class acp.KillTerminalCommandRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The session ID for this request.
---@field terminalId string The ID of the terminal to kill.

---Response to terminal/kill command method
---@class acp.KillTerminalCommandResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)

---Request parameters for loading an existing session.
---
---Only available if the Agent supports the `loadSession` capability.
---
---See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
---@class acp.LoadSessionRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field cwd string The working directory for this session.
---@field mcpServers acp.McpServer[] List of MCP servers to connect to for this session.
---@field sessionId acp.SessionId The ID of the session to load.

---Response from loading an existing session.
---@class acp.LoadSessionResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field configOptions acp.SessionConfigOption[]|nil? Initial session configuration options if supported by the Agent.
---@field modes acp.SessionModeState|nil? Initial mode state if supported by the Agent  See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)

---MCP capabilities supported by the agent
---@class acp.McpCapabilities
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field http boolean? Agent supports [`McpServer::Http`].
---@field sse boolean? Agent supports [`McpServer::Sse`].

---Configuration for connecting to an MCP (Model Context Protocol) server.
---
---MCP servers provide tools and context that the agent can use when
---processing prompts.
---
---See protocol docs: [MCP Servers](https://agentclientprotocol.com/protocol/session-setup#mcp-servers)

---HTTP transport configuration  Only available when the Agent capabilities indicate `mcp_capabilities.http` is `true`.
---@class acp.McpServer_1 : acp.McpServerHttp
---@field type "http"

---SSE transport configuration  Only available when the Agent capabilities indicate `mcp_capabilities.sse` is `true`.
---@class acp.McpServer_2 : acp.McpServerSse
---@field type "sse"

---Stdio transport configuration  All Agents MUST support this transport.
---@class acp.McpServer_stdio : acp.McpServerStdio
---@alias acp.McpServer acp.McpServer_1|acp.McpServer_2|acp.McpServer_stdio

---HTTP transport configuration for MCP.
---@class acp.McpServerHttp
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field headers acp.HttpHeader[] HTTP headers to set when making requests to the MCP server.
---@field name string Human-readable name identifying this MCP server.
---@field url string URL to the MCP server.

---SSE transport configuration for MCP.
---@class acp.McpServerSse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field headers acp.HttpHeader[] HTTP headers to set when making requests to the MCP server.
---@field name string Human-readable name identifying this MCP server.
---@field url string URL to the MCP server.

---Stdio transport configuration for MCP.
---@class acp.McpServerStdio
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field args string[] Command-line arguments to pass to the MCP server.
---@field command string Path to the MCP server executable.
---@field env acp.EnvVariable[] Environment variables to set when launching the MCP server.
---@field name string Human-readable name identifying this MCP server.

---Request parameters for creating a new session.
---
---See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
---@class acp.NewSessionRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field cwd string The working directory for this session. Must be an absolute path.
---@field mcpServers acp.McpServer[] List of MCP (Model Context Protocol) servers the agent should connect to.

---Response from creating a new session.
---
---See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
---@class acp.NewSessionResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field configOptions acp.SessionConfigOption[]|nil? Initial session configuration options if supported by the Agent.
---@field modes acp.SessionModeState|nil? Initial mode state if supported by the Agent  See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
---@field sessionId acp.SessionId Unique identifier for the created session.  Used in all subsequent requests for this conversation.

---An option presented to the user when requesting permission.
---@class acp.PermissionOption
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field kind acp.PermissionOptionKind Hint about the nature of this permission option.
---@field name string Human-readable label to display to the user.
---@field optionId acp.PermissionOptionId Unique identifier for this permission option.

---Unique identifier for a permission option.
---@alias acp.PermissionOptionId string

---The type of permission option being presented to the user.
---
---Helps clients choose appropriate icons and UI treatment.
---@alias acp.PermissionOptionKind "allow_once"|"allow_always"|"reject_once"|"reject_always"

---An execution plan for accomplishing complex tasks.
---
---Plans consist of multiple entries representing individual tasks or goals.
---Agents report plans to clients to provide visibility into their execution strategy.
---Plans can evolve during execution as the agent discovers new requirements or completes tasks.
---
---See protocol docs: [Agent Plan](https://agentclientprotocol.com/protocol/agent-plan)
---@class acp.Plan
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field entries acp.PlanEntry[] The list of tasks to be accomplished.  When updating a plan, the agent must send a complete list of all entries with their current status. The client replaces the entire plan with each update.

---A single entry in the execution plan.
---
---Represents a task or goal that the assistant intends to accomplish
---as part of fulfilling the user's request.
---See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
---@class acp.PlanEntry
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content string Human-readable description of what this task aims to accomplish.
---@field priority acp.PlanEntryPriority The relative importance of this task. Used to indicate which tasks are most critical to the overall goal.
---@field status acp.PlanEntryStatus Current execution status of this task.

---Priority levels for plan entries.
---
---Used to indicate the relative importance or urgency of different
---tasks in the execution plan.
---See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
---@alias acp.PlanEntryPriority "high"|"medium"|"low"

---Status of a plan entry in the execution flow.
---
---Tracks the lifecycle of each task from planning through completion.
---See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
---@alias acp.PlanEntryStatus "pending"|"in_progress"|"completed"

---Prompt capabilities supported by the agent in `session/prompt` requests.
---
---Baseline agent functionality requires support for [`ContentBlock::Text`]
---and [`ContentBlock::ResourceLink`] in prompt requests.
---
---Other variants must be explicitly opted in to.
---Capabilities for different types of content in prompt requests.
---
---Indicates which content types beyond the baseline (text and resource links)
---the agent can process.
---
---See protocol docs: [Prompt Capabilities](https://agentclientprotocol.com/protocol/initialization#prompt-capabilities)
---@class acp.PromptCapabilities
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field audio boolean? Agent supports [`ContentBlock::Audio`].
---@field embeddedContext boolean? Agent supports embedded context in `session/prompt` requests.  When enabled, the Client is allowed to include [`ContentBlock::Resource`] in prompt requests for pieces of context that are referenced in the message.
---@field image boolean? Agent supports [`ContentBlock::Image`].

---Request parameters for sending a user prompt to the agent.
---
---Contains the user's message and any additional context.
---
---See protocol docs: [User Message](https://agentclientprotocol.com/protocol/prompt-turn#1-user-message)
---@class acp.PromptRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field prompt acp.ContentBlock[] The blocks of content that compose the user's message.  As a baseline, the Agent MUST support [`ContentBlock::Text`] and [`ContentBlock::ResourceLink`], while other variants are optionally enabled via [`PromptCapabilities`].  The Client MUST adapt its interface according to [`PromptCapabilities`].  The client MAY include referenced pieces of context as either [`ContentBlock::Resource`] or [`ContentBlock::ResourceLink`].  When available, [`ContentBlock::Resource`] is preferred as it avoids extra round-trips and allows the message to include pieces of context from sources the agent may not have access to.
---@field sessionId acp.SessionId The ID of the session to send this user message to

---Response from processing a user prompt.
---
---See protocol docs: [Check for Completion](https://agentclientprotocol.com/protocol/prompt-turn#4-check-for-completion)
---@class acp.PromptResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field stopReason acp.StopReason Indicates why the agent stopped processing the turn.

---Protocol version identifier.
---
---This version is only bumped for breaking changes.
---Non-breaking changes should be introduced via capabilities.
---@alias acp.ProtocolVersion number

---Request to read content from a text file.
---
---Only available if the client supports the `fs.readTextFile` capability.
---@class acp.ReadTextFileRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field limit number|nil? Maximum number of lines to read.
---@field line number|nil? Line number to start reading from (1-based).
---@field path string Absolute path to the file to read.
---@field sessionId acp.SessionId The session ID for this request.

---Response containing the contents of a text file.
---@class acp.ReadTextFileResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content string

---Request to release a terminal and free its resources.
---@class acp.ReleaseTerminalRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The session ID for this request.
---@field terminalId string The ID of the terminal to release.

---Response to terminal/release method
---@class acp.ReleaseTerminalResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)

---JSON RPC Request Id
---
---An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]
---
---The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.
---
---[1] The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id. Also, because JSON-RPC 1.0 uses an id value of Null for Notifications this could cause confusion in handling.
---
---[2] Fractional parts may be problematic, since many decimal fractions cannot be represented exactly as binary fractions.

---@class acp.RequestId_Null

---@class acp.RequestId_Number

---@class acp.RequestId_Str
---@alias acp.RequestId acp.RequestId_Null|acp.RequestId_Number|acp.RequestId_Str

---The outcome of a permission request.

---The prompt turn was cancelled before the user responded.  When a client sends a `session/cancel` notification to cancel an ongoing prompt turn, it MUST respond to all pending `session/request_permission` requests with this `Cancelled` outcome.  See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
---@class acp.RequestPermissionOutcome_1
---@field outcome "cancelled"

---The user selected one of the provided options.
---@class acp.RequestPermissionOutcome_2 : acp.SelectedPermissionOutcome
---@field outcome "selected"
---@alias acp.RequestPermissionOutcome acp.RequestPermissionOutcome_1|acp.RequestPermissionOutcome_2

---Request for user permission to execute a tool call.
---
---Sent when the agent needs authorization before performing a sensitive operation.
---
---See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
---@class acp.RequestPermissionRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field options acp.PermissionOption[] Available permission options for the user to choose from.
---@field sessionId acp.SessionId The session ID for this request.
---@field toolCall acp.ToolCallUpdate Details about the tool call requiring permission.

---Response to a permission request.
---@class acp.RequestPermissionResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field outcome acp.RequestPermissionOutcome The user's decision on the permission request.

---A resource that the server is capable of reading, included in a prompt or tool call result.
---@class acp.ResourceLink
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field annotations acp.Annotations|nil?
---@field description string|nil?
---@field mimeType string|nil?
---@field name string
---@field size number|nil?
---@field title string|nil?
---@field uri string

---The sender or recipient of messages and data in a conversation.
---@alias acp.Role string

---The user selected one of the provided options.
---@class acp.SelectedPermissionOutcome
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field optionId acp.PermissionOptionId The ID of the option the user selected.

---Session capabilities supported by the agent.
---
---As a baseline, all Agents **MUST** support `session/new`, `session/prompt`, `session/cancel`, and `session/update`.
---
---Optionally, they **MAY** support other session methods and notifications by specifying additional capabilities.
---
---Note: `session/load` is still handled by the top-level `load_session` capability. This will be unified in future versions of the protocol.
---
---See protocol docs: [Session Capabilities](https://agentclientprotocol.com/protocol/initialization#session-capabilities)
---@class acp.SessionCapabilities
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)

---Unique identifier for a session configuration option value group.
---@alias acp.SessionConfigGroupId string

---Unique identifier for a session configuration option.
---@alias acp.SessionConfigId string

---A session configuration option selector and its current state.

---Single-value selector (dropdown).
---@class acp.SessionConfigOption_1 : acp.SessionConfigSelect
---@field type "select"
---@alias acp.SessionConfigOption acp.SessionConfigOption_1

---Semantic category for a session configuration option.
---
---This is intended to help Clients distinguish broadly common selectors (e.g. model selector vs
---session mode selector vs thought/reasoning level) for UX purposes (keyboard shortcuts, icons,
---placement). It MUST NOT be required for correctness. Clients MUST handle missing or unknown
---categories gracefully.
---
---Category names beginning with `_` are free for custom use, like other ACP extension methods.
---Category names that do not begin with `_` are reserved for the ACP spec.

---Unknown / uncategorized selector.
---@class acp.SessionConfigOptionCategory_other
---@alias acp.SessionConfigOptionCategory string|string|string|acp.SessionConfigOptionCategory_other

---A single-value selector (dropdown) session configuration option payload.
---@class acp.SessionConfigSelect
---@field currentValue acp.SessionConfigValueId The currently selected value.
---@field options acp.SessionConfigSelectOptions The set of selectable options.

---A group of possible values for a session configuration option.
---@class acp.SessionConfigSelectGroup
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field group acp.SessionConfigGroupId Unique identifier for this group.
---@field name string Human-readable label for this group.
---@field options acp.SessionConfigSelectOption[] The set of option values in this group.

---A possible value for a session configuration option.
---@class acp.SessionConfigSelectOption
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field description string|nil? Optional description for this option value.
---@field name string Human-readable label for this option value.
---@field value acp.SessionConfigValueId Unique identifier for this option value.

---Possible values for a session configuration option.

---A flat list of options with no grouping.
---@alias acp.SessionConfigSelectOptions_Ungrouped acp.SessionConfigSelectOption[]

---A list of options grouped under headers.
---@alias acp.SessionConfigSelectOptions_Grouped acp.SessionConfigSelectGroup[]
---@alias acp.SessionConfigSelectOptions acp.SessionConfigSelectOptions_Ungrouped|acp.SessionConfigSelectOptions_Grouped

---Unique identifier for a session configuration option value.
---@alias acp.SessionConfigValueId string

---A unique identifier for a conversation session between a client and agent.
---
---Sessions maintain their own context, conversation history, and state,
---allowing multiple independent interactions with the same agent.
---
---See protocol docs: [Session ID](https://agentclientprotocol.com/protocol/session-setup#session-id)
---@alias acp.SessionId string

---A mode the agent can operate in.
---
---See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
---@class acp.SessionMode
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field description string|nil?
---@field id acp.SessionModeId
---@field name string

---Unique identifier for a Session Mode.
---@alias acp.SessionModeId string

---The set of modes and the one currently active.
---@class acp.SessionModeState
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field availableModes acp.SessionMode[] The set of modes that the Agent can operate in
---@field currentModeId acp.SessionModeId The current mode the Agent is in.

---Notification containing a session update from the agent.
---
---Used to stream real-time progress and results during prompt processing.
---
---See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
---@class acp.SessionNotification
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The ID of the session this update pertains to.
---@field update acp.SessionUpdate The actual update content.

---Different types of updates that can be sent during session processing.
---
---These updates provide real-time feedback about the agent's progress.
---
---See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)

---A chunk of the user's message being streamed.
---@class acp.SessionUpdate_1 : acp.ContentChunk
---@field sessionUpdate "user_message_chunk"

---A chunk of the agent's response being streamed.
---@class acp.SessionUpdate_2 : acp.ContentChunk
---@field sessionUpdate "agent_message_chunk"

---A chunk of the agent's internal reasoning being streamed.
---@class acp.SessionUpdate_3 : acp.ContentChunk
---@field sessionUpdate "agent_thought_chunk"

---Notification that a new tool call has been initiated.
---@class acp.SessionUpdate_4 : acp.ToolCall
---@field sessionUpdate "tool_call"

---Update on the status or results of a tool call.
---@class acp.SessionUpdate_5 : acp.ToolCallUpdate
---@field sessionUpdate "tool_call_update"

---The agent's execution plan for complex tasks. See protocol docs: [Agent Plan](https://agentclientprotocol.com/protocol/agent-plan)
---@class acp.SessionUpdate_6 : acp.Plan
---@field sessionUpdate "plan"

---Available commands are ready or have changed
---@class acp.SessionUpdate_7 : acp.AvailableCommandsUpdate
---@field sessionUpdate "available_commands_update"

---The current mode of the session has changed  See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
---@class acp.SessionUpdate_8 : acp.CurrentModeUpdate
---@field sessionUpdate "current_mode_update"

---Session configuration options have been updated.
---@class acp.SessionUpdate_9 : acp.ConfigOptionUpdate
---@field sessionUpdate "config_option_update"
---@alias acp.SessionUpdate acp.SessionUpdate_1|acp.SessionUpdate_2|acp.SessionUpdate_3|acp.SessionUpdate_4|acp.SessionUpdate_5|acp.SessionUpdate_6|acp.SessionUpdate_7|acp.SessionUpdate_8|acp.SessionUpdate_9

---Request parameters for setting a session configuration option.
---@class acp.SetSessionConfigOptionRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field configId acp.SessionConfigId The ID of the configuration option to set.
---@field sessionId acp.SessionId The ID of the session to set the configuration option for.
---@field value acp.SessionConfigValueId The ID of the configuration option value to set.

---Response to `session/set_config_option` method.
---@class acp.SetSessionConfigOptionResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field configOptions acp.SessionConfigOption[] The full set of configuration options and their current values.

---Request parameters for setting a session mode.
---@class acp.SetSessionModeRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field modeId acp.SessionModeId The ID of the mode to set.
---@field sessionId acp.SessionId The ID of the session to set the mode for.

---Response to `session/set_mode` method.
---@class acp.SetSessionModeResponse
---@field _meta table|nil?

---Reasons why an agent stops processing a prompt turn.
---
---See protocol docs: [Stop Reasons](https://agentclientprotocol.com/protocol/prompt-turn#stop-reasons)
---@alias acp.StopReason "end_turn"|"max_tokens"|"max_turn_requests"|"refusal"|"cancelled"

---Embed a terminal created with `terminal/create` by its id.
---
---The terminal must be added before calling `terminal/release`.
---
---See protocol docs: [Terminal](https://agentclientprotocol.com/protocol/terminals)
---@class acp.Terminal
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field terminalId string

---Exit status of a terminal command.
---@class acp.TerminalExitStatus
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field exitCode number|nil? The process exit code (may be null if terminated by signal).
---@field signal string|nil? The signal that terminated the process (may be null if exited normally).

---Request to get the current output and status of a terminal.
---@class acp.TerminalOutputRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The session ID for this request.
---@field terminalId string The ID of the terminal to get output from.

---Response containing the terminal output and exit status.
---@class acp.TerminalOutputResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field exitStatus acp.TerminalExitStatus|nil? Exit status if the command has completed.
---@field output string The terminal output captured so far.
---@field truncated boolean Whether the output was truncated due to byte limits.

---Text provided to or from an LLM.
---@class acp.TextContent
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field annotations acp.Annotations|nil?
---@field text string

---Text-based resource contents.
---@class acp.TextResourceContents
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field mimeType string|nil?
---@field text string
---@field uri string

---Represents a tool call that the language model has requested.
---
---Tool calls are actions that the agent executes on behalf of the language model,
---such as reading files, executing code, or fetching data from external sources.
---
---See protocol docs: [Tool Calls](https://agentclientprotocol.com/protocol/tool-calls)
---@class acp.ToolCall
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content acp.ToolCallContent[]? Content produced by the tool call.
---@field kind acp.ToolKind? The category of tool being invoked. Helps clients choose appropriate icons and UI treatment.
---@field locations acp.ToolCallLocation[]? File locations affected by this tool call. Enables "follow-along" features in clients.
---@field rawInput any? Raw input parameters sent to the tool.
---@field rawOutput any? Raw output returned by the tool.
---@field status acp.ToolCallStatus? Current execution status of the tool call.
---@field title string Human-readable title describing what the tool is doing.
---@field toolCallId acp.ToolCallId Unique identifier for this tool call within the session.

---Content produced by a tool call.
---
---Tool calls can produce different types of content including
---standard content blocks (text, images) or file diffs.
---
---See protocol docs: [Content](https://agentclientprotocol.com/protocol/tool-calls#content)

---Standard content block (text, images, resources).
---@class acp.ToolCallContent_1 : acp.Content
---@field type "content"

---File modification shown as a diff.
---@class acp.ToolCallContent_2 : acp.Diff
---@field type "diff"

---Embed a terminal created with `terminal/create` by its id.  The terminal must be added before calling `terminal/release`.  See protocol docs: [Terminal](https://agentclientprotocol.com/protocol/terminals)
---@class acp.ToolCallContent_3 : acp.Terminal
---@field type "terminal"
---@alias acp.ToolCallContent acp.ToolCallContent_1|acp.ToolCallContent_2|acp.ToolCallContent_3

---Unique identifier for a tool call within a session.
---@alias acp.ToolCallId string

---A file location being accessed or modified by a tool.
---
---Enables clients to implement "follow-along" features that track
---which files the agent is working with in real-time.
---
---See protocol docs: [Following the Agent](https://agentclientprotocol.com/protocol/tool-calls#following-the-agent)
---@class acp.ToolCallLocation
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field line number|nil? Optional line number within the file.
---@field path string The file path being accessed or modified.

---Execution status of a tool call.
---
---Tool calls progress through different statuses during their lifecycle.
---
---See protocol docs: [Status](https://agentclientprotocol.com/protocol/tool-calls#status)
---@alias acp.ToolCallStatus "pending"|"in_progress"|"completed"|"failed"

---An update to an existing tool call.
---
---Used to report progress and results as tools execute. All fields except
---the tool call ID are optional - only changed fields need to be included.
---
---See protocol docs: [Updating](https://agentclientprotocol.com/protocol/tool-calls#updating)
---@class acp.ToolCallUpdate
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content acp.ToolCallContent[]|nil? Replace the content collection.
---@field kind acp.ToolKind|nil? Update the tool kind.
---@field locations acp.ToolCallLocation[]|nil? Replace the locations collection.
---@field rawInput any? Update the raw input.
---@field rawOutput any? Update the raw output.
---@field status acp.ToolCallStatus|nil? Update the execution status.
---@field title string|nil? Update the human-readable title.
---@field toolCallId acp.ToolCallId The ID of the tool call being updated.

---Categories of tools that can be invoked.
---
---Tool kinds help clients choose appropriate icons and optimize how they
---display tool execution progress.
---
---See protocol docs: [Creating](https://agentclientprotocol.com/protocol/tool-calls#creating)
---@alias acp.ToolKind "read"|"edit"|"delete"|"move"|"search"|"execute"|"think"|"fetch"|"switch_mode"|"other"

---All text that was typed after the command name is provided as input.
---@class acp.UnstructuredCommandInput
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field hint string A hint to display when the input hasn't been provided yet

---Request to wait for a terminal command to exit.
---@class acp.WaitForTerminalExitRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field sessionId acp.SessionId The session ID for this request.
---@field terminalId string The ID of the terminal to wait for.

---Response containing the exit status of a terminal command.
---@class acp.WaitForTerminalExitResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field exitCode number|nil? The process exit code (may be null if terminated by signal).
---@field signal string|nil? The signal that terminated the process (may be null if exited normally).

---Request to write content to a text file.
---
---Only available if the client supports the `fs.writeTextFile` capability.
---@class acp.WriteTextFileRequest
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
---@field content string The text content to write to the file.
---@field path string Absolute path to the file to write.
---@field sessionId acp.SessionId The session ID for this request.

---Response to `fs/write_text_file`
---@class acp.WriteTextFileResponse
---@field _meta table|nil? The _meta property is reserved by ACP to allow clients and agents to attach additional metadata to their interactions. Implementations MUST NOT make assumptions about values at these keys.  See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
