#!/usr/bin/env -S nvim -l
-- Meta JSON to Lua Table Converter
-- Converts meta.json to a Lua module with tables

local fn = vim.fn
local meta_json_file = "schema/meta.json"
local output_lua_file = "lua/acp/meta.lua"

-- Read the JSON file
local meta_json = fn.readfile(meta_json_file)
local meta_data = fn.json_decode(meta_json)

local meta_lua = "--- This file is generated by ./scripts/convert_meta.lua.\n--- DO NOT edit it manually\nreturn "
	.. vim.inspect(meta_data, { indent = "\t" })
fn.writefile(vim.split(meta_lua, "\n"), output_lua_file)
